endpoints:
  - name: integro-consulting-contact
    group: core
    url: "https://www.integroconsulting.se/contact/"
    interval: 5m
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 500"

  - name: integro-consulting-work
    group: core
    url: "https://www.integroconsulting.se/work-at-integro-integro-consulting/"
    interval: 5m
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 500"

  - name: integro-consulting-about-us
    group: core
    url: "https://www.integroconsulting.se/about-us-integro-consulting/#ws-block-about-with-features-k2sYA8BP"
    interval: 5m
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 500"

  - name: integro-consulting-expertise
    group: core
    url: "https://www.integroconsulting.se/areas-of-expertise-integro-consulting-kopiera/"
    interval: 1h
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 500"

  - name: integro-consulting
    group: core
    url: "https://www.integroconsulting.se/"
    interval: 1h
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 500"
