endpoints:
  - name: 
    group: ecarx-software-services
    url: "https://www.ecarxgroup.com/software-services/"
    interval: 5m
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 500"

  - name: ecarx-news
    group: core
    url: "https://www.ecarxgroup.com/news/"
    interval: 5m
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 500"

  - name: ecarx-insights
    group: core
    url: "https://www.ecarxgroup.com/insights/"
    interval: 5m
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 500"

  - name: ecarx-about-us
    group: core
    url: "https://www.ecarxgroup.com/about-us/"
    interval: 1h
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 500"

  - name: ecarx-main-page
    group: core
    url: "https://www.ecarxgroup.com/"
    interval: 1h
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 500"
