endpoints:
  - name: 
    group: capgemini-new
    url: "https://www.capgemini.com/se-en/news/"
    interval: 5m
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 500"

  - name: capgemini-industries
    group: core
    url: "https://www.capgemini.com/se-en/industries/"
    interval: 5m
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 500"

  - name: capgemini-insights
    group: core
    url: "https://www.capgemini.com/se-en/insights/"
    interval: 5m
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 500"

  - name: capgemini-about-us
    group: core
    url: "https://www.capgemini.com/se-en/about-us/"
    interval: 1h
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 500"

  - name: capgemini-main-page
    group: core
    url: "https://www.capgemini.com/se-en/"
    interval: 1h
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 500"
